### ISSUE TITLE
Apache Event模式似乎会导致不定时报错

### ISSUE THREAD

**Issue by chickendhj** [liexusong/php-beast#109]
服务器Apache2.4 php 5.4（TS）
require不定时提示打开文件失败(Failed opening...A.php)刷新后正常，再刷新几次后可能又报错
页面为多层require嵌套 将A.php传为明文后 不会再报错，但是又会有其他文件提示相似的错误 
尝试过各种版本 各种重装模块 php
最后发现Apache MPM为Event会导致这个问题
改为Prefork后目前未发现问题

**Comment by liexusong** [comment]
这个扩展不支持多线程模式的

**Comment by chickendhj** [comment]
> 这个扩展不支持多线程模式的

OK,虽然可能用apache PHP的少了，希望在README上注释一下
