### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by joostshao** [liexusong/php-beast#14]
laravel5  整体加密的结果

**Comment by joostshao** [comment]
而且解析执行的速度很慢

**Comment by LiXunGuan** [comment]
@joostshao 你现在解决了吗？我也在找加密程序给laravel5加密

**Comment by joostshao** [comment]
没有，其实我们业务暂时没这种需求，是不是可以用类似apc, dump的形式呢?

**Comment by LiXunGuan** [comment]
@joostshao 我写了商业程序，需要找套加密工具（付费也行）
