### ISSUE TITLE
建议编译出的文件名自动附加网卡部分字符和过期日期

### ISSUE THREAD

**Issue by hustxay** [liexusong/php-beast#32]
由于产品最终可能部署到多台机器上去，
编译出的文件多了就容易在机器匹配上出错。
因此建议在用不同的网卡和过期日期信息编译时，在编译出的文件上附加上这些信息，
比如beast_xxxxxx_20991231.so「网卡取后6位」

在服务器配置再修改为beast.so或者只直接用extension=beast_xxxxxx_20991231.so配置

**Comment by liexusong** [comment]
自己改名不就可以了吗？
