### ISSUE TITLE
不知道beast最大支持多大PHP文件的加密

### ISSUE THREAD

**Issue by igge2015** [liexusong/php-beast#36]
刚才有一个Issues说最大只支持64KB，不知道新版本还是有这样的限制吗？

**Comment by liexusong** [comment]
最大支持64k的文件

**Comment by igge2015** [comment]
恩，谢谢。
那个怎么编译windows版本，编译linux倒是挺方便的

**Comment by liexusong** [comment]
windows不能编译，因为扩展使用了很多linux的api

**Comment by igge2015** [comment]
恩，不过为什么PHP7也不支持，用了PHP7的那个标签下的文件编译出来放进去504，GCC是6.2版本的，然后用master下面的无法编译
