### ISSUE TITLE
关于expire过期时间无效的问题

### ISSUE THREAD

**Issue by itbirds** [liexusong/php-beast#37]
你好，
       我在配置安装好php-beast之后，使用了tools目录下的configure.ini配置了expire过期时间，重新加密了文件，问题是，当前时间超过了expire时间，加密的文件依然可以运行。首先我怀疑是自己PHP的时区设置问题，在加密文件打印出了，当前时间，发现时区是没错的，也尝试过把expire设置为时间戳，也没有用。我找到你的tools目录下的encode_files.php的75行，发现是这里调用扩展的beast_encode_file函数，然后查看了，源文件的beast.c文件，发现这个函数可以设置一个expire过期时间，我在encode_files.php的75行加上了expire过期时间（时间戳的格式）beast_encode_file($path, $new_path,$expire)，
再次加密文件，运行之后依然没有效果。
请问，是我配置的地方有问题还是缺少响应的配置。

**Comment by liexusong** [comment]
已解决

**Comment by itbirds** [comment]
非常感谢！
