### ISSUE TITLE
PHP Fatal error:  Unable to start beast module in Unknown on line 0

### ISSUE THREAD

**Issue by jiaowang** [liexusong/php-beast#5]
在进行加密后,项目正常运行,但不知什么情况下出现了这个错误！

PHP Fatal error:  Unable to start beast module in Unknown on line 0. 

执行外部命令php失效,重启php-fpm也是这个错误导致无法启动。

解决方法只能是取消这个模块或者重启服务器.这个有点...

**Comment by ynvince** [comment]
我也遇到，请问下是如何解决这个问题的？
