### ISSUE TITLE
windows版本下会出现循环输出问题

### ISSUE THREAD

**Issue by ChanpoHui** [liexusong/php-beast#58]
PHP版本5.6，对应beast版本php 5.6.x vc11 x86 nts

如果代码里面有require或者命名空间使用语法use，则会出错。

例如：

```
<?php

echo '1234';

require __DIR__ . '/_release.inc.php';

?>
```

会循环输出1234

**Comment by imaben** [comment]
_release.inc.php里是什么内容？

**Comment by ChanpoHui** [comment]
_release.inc.php里是什么内容？

```
<?php
define('APP_RELEASE', '20170307');
```

**Comment by imaben** [comment]
@ChanpoHui 已经解决了，你可以先到https://github.com/imaben/php-beast-binaries 下载，后面会把改后的源码更新上去！

**Comment by ChanpoHui** [comment]
@imaben 是的，谢谢~
