### ISSUE TITLE
关于在ubuntu中为php7扩展beast后，运行php报错的问题

### ISSUE THREAD

**Issue by chuchaochen** [liexusong/php-beast#75]
您好：
      我在php7中扩展了beast，但是运行php报错：
root@ubuntu:/home# php -v
PHP Fatal error:  PHP Startup: Not allowed run at this computer in Unknown on line 0
PHP Fatal error:  Unable to start beast module in Unknown on line 0

我在php.ini中做了如下配置：
extension=beast.so
beast.cache_size = 100
beast.log_file = "/home/beast/log"
beast.log_user = "root"
beast.enable = On

请问这是为什么？

**Comment by imaben** [comment]
Not allowed run at this computer

**Comment by imaben** [comment]
编译的时候你绑定网卡了吧

**Comment by chuchaochen** [comment]
我去掉了网卡的绑定，ok了。 谢谢~
我是用的云服务器， 绑定网卡会有问题吗？

**Comment by imaben** [comment]
没啥问题！
