### ISSUE TITLE
Call to undefined function beast_encode_file

### ISSUE THREAD

**Issue by cn163** [liexusong/php-beast#83]
[root@w'w'w tools]# php encode_files.php
Source code path: /data/www
Destination code path: /data/beast
Expire time: 2099-12-31
------------- start process -------------

Fatal error: Call to undefined function beast_encode_file() in /data/php-beast-master/tools/encode_files.php on line 78
这是什么原因

**Comment by cn163** [comment]
beast log:[05 Jul 11:42:08] DEBUG: Beast module was initialized

**Comment by imaben** [comment]
php -m

**Comment by cn163** [comment]
phpinfo():
beast V2.7 support	enabled

**Comment by liexusong** [comment]
估计是php.ini没有引入的问题

**Comment by liexusong** [comment]
在启动php的时候指定一下php.ini，例如： php -c /xxx/xxx/php.ini encode_files.php

**Comment by cn163** [comment]
./php-fpm -c /usr/local/php/etc/php.ini
配置是媒问题的

**Comment by liexusong** [comment]
你这个是fpm啊，跟cli是不一样的

**Comment by cn163** [comment]
照你的方法指定配置可以了，谢谢
[root@www tools]# php -c /usr/local/php/etc/php.ini encode_files.php
Source code path: /home/www
Destination code path: /home/test
Expire time: 2099-12-31
------------- start process -------------
Processed encrypt files [100%] - 100%
Finish processed encrypt files, used 22.521861 seconds

**Comment by cn163** [comment]
问题已解决
