### ISSUE TITLE
alpine下编译完成后，fpm不能正常加载 beast.so 扩展

### ISSUE THREAD

**Issue by imjawe** [liexusong/php-beast#86]
你好，
基于php的 docker 官方镜像，试了 7.1-fpm 和 7.1-fpm-alpine
debian jessie 下完成后加载正常，功能正常
alpine下编译成功，但 beast.so 不能正常加载，已测试多个版本，仍如此，求指导，
`PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/beast.so' - Error relocating /usr/local/lib/php/extensions/no-debug-non-zts-20160303/beast.so: backtrace_symbols: symbol not found in Unknown on line 0
[03-Aug-2017 10:08:48] NOTICE: fpm is running, pid 1
[03-Aug-2017 10:08:48] NOTICE: ready to handle connections`

**Comment by liexusong** [comment]
这是因为backtrace_symbols这个函数没有，可以把这个调用去掉

**Comment by imjawe** [comment]
感谢回复，注释代码块后，不再报错，
但仍是不解，原因应该在 alpine 上面，
关键是 apk add libexecinfo 或 libunwind-dev，
编辑都过了，怎么就加载不到这两个函数呢？求指导，

**Comment by liexusong** [comment]
这个我也不清楚，因为这个函数是Linux特有的，有些类Unix环境也不一定有

**Comment by lkq0929** [comment]
基于php的 docker 官方镜像，7.1-fpm-alpine
下完成后加载正常，功能正常
alpine下编译成功，但 beast.so 不能正常加载
