### ISSUE TITLE
启动php报错backtrace_symbols: symbol not found in Unknown on line 0

### ISSUE THREAD

**Issue by miaoyingting** [liexusong/php-beast#93]
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20121212/beast.so' - Error relocating /usr/local/lib/php/extensions/no-debug-non-zts-20121212/beast.so: backtrace_symbols: symbol not found in Unknown on line 0
Extension 'beast' not present

**Comment by fanybook** [comment]
我也是这个问题，有解决吗，怎么关闭了
